repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: check-merge-conflict

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.12.0
    hooks:
      - id: pretty-format-java
        args: [--aosp, --autofix]

  - repo: local
    hooks:
      - id: checkstyle
        name: Google Checkstyle
        entry: mvn checkstyle:check -q
        language: system
        files: '\.java$'
        pass_filenames: false
